name: Python package

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test_conda:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda bash
        shell: bash -l {0}
        run: export CONDA_ALWAYS_YES="true" && conda env create --file environment.yml --name molsim_ml && conda activate molsim_ml && python test/test.py
